tempDir: /tmp/backups
deltasPerFile: 10000
backupThreshold: 100
concurrentBasebackups: 5
trackNewTables: true
slotname: myslot
publication: mypub
sendStatusOnCommit: false
initialBasebackup: true
fsync: false
archiveDir: /tmp/backup2
periodBetweenBackups: 12h
oldDeltaBackupTrigger: 24h
db:
    host: 127.0.0.1
    port: 5432
    database: demo
    user: mkabilov

